apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthai-backend
  namespace: synthai
  labels:
    app: synthai-backend
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: synthai-backend
  template:
    metadata:
      labels:
        app: synthai-backend
        version: v1.0.0
    spec:
      containers:
      - name: backend
        image: ghcr.io/synthai/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: synthai-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: synthai-secrets
              key: redis-url
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: synthai-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: synthai-secrets
              key: openai-api-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: synthai-secrets
              key: stripe-secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: synthai-backend
  namespace: synthai
spec:
  selector:
    app: synthai-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
