version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: synthai
      POSTGRES_USER: synthai_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - synthai-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - synthai-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://synthai_user:${DB_PASSWORD:-changeme}@postgres:5432/synthai
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - synthai-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - synthai-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - synthai-network

volumes:
  postgres_data:

networks:
  synthai-network:
    driver: bridge
